package local:zappy;

interface host-api {
  use system.{text-segment};

  host-log: func(msg: string);
  host-system-command: func(cmd: string, args: list<string>) -> list<text-segment>;

  emit-event: func(event-name: string, payload: string);
  host-subscribe: func(event-name: string);

  host-set-state: func(key: string, value: list<u8>);
  host-get-state: func(key: string) -> option<list<u8>>;
}

world ui-world {
  import host-api;

  use input.{engine-context, input-action, input-state};
  use graphic.{render-command};
  use command.{command-desc, response-command};
  use system.{text-segment};

  export handle-input: func(state: input-state);
  export run-command: func(cmd: string, args: list<string>) -> response-command;
  export update-module: func(time: f32, dt: f32, w: f32, h: f32) -> list<render-command>;

  export get-commands: func() -> list<command-desc>;
  export accept-log: func(segments: list<text-segment>);

  export serialize: func() -> list<u8>;
  export deserialize: func(state: list<u8>);

  export handle-event: func(event-name: string, payload: string);
}

world cube-world {
  import host-api;

  use input.{engine-context, input-action, delta, input-state};
  use graphic.{render-command, text-align};
  use command.{command-desc, response-command};

  export handle-input: func(state: input-state);
  export get-commands: func() -> list<command-desc>;
  export run-command: func(cmd: string, args: list<string>) -> response-command;
  export update-module: func(time: f32, dt: f32, w: f32, h: f32) -> list<render-command>;

  export serialize: func() -> list<u8>;
  export deserialize: func(state: list<u8>);

  export handle-event: func(event-name: string, payload: string);
}
