package local:zappy;

interface graphic {
  record color { r: u8, g: u8, b: u8, a: u8 }
  record rect-cmd { x: f32, y: f32, w: f32, h: f32, color: color, rotation: f32 }
  record text-cmd { text: string, x: f32, y: f32, size: f32, color: color }

  variant render-command {
    rect(rect-cmd),
    text(text-cmd),
  }
}
