#!/usr/bin/env python3

import csv
from sys import argv
import pandas as pd

SAMPLE_INTERVAL = 50

if __name__ == "__main__":
    csv_name = argv[1]
    df = pd.read_csv(csv_name)
    sampled_df = df[df["gen"] % SAMPLE_INTERVAL == 0]

    output_path = csv_name.replace(".csv", "_sample.csv")
    sampled_df.to_csv(output_path, index=False)
